# Generated by Django 4.0.2 on 2022-03-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecSys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacontent',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
