# Generated by Django 4.0.2 on 2022-04-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecSys', '0003_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='file_id',
        ),
        migrations.AddField(
            model_name='userdata',
            name='uploadedFile',
            field=models.FileField(default=1, upload_to='Uploaded Files/'),
            preserve_default=False,
        ),
    ]
